version: "3.8"

services:
  web-crm:
    build:
      context: ../apps/web-crm
      dockerfile: Dockerfile
    ports:
      - "3005:3000"

  api-crm:
    build:
      context: ../apps/api-crm
      dockerfile: Dockerfile
    ports:
      - "5005:8080"

  api-ai-analytics:
    build:
      context: ../apps/api-ai-analytics
      dockerfile: Dockerfile
    ports:
      - "4005:4005"
